meta:
  title: Redocly Training
  description: The best API documentation generator ever.
  siteUrl: https://portal-demo.redoc.ly
  keywords: redocly developer portal, api portal starter, api reference docs
headerIcon: ./images/hpe.svg
enableToc: true
oasDefinitions:
  petstore: ./openapi/petstore.yaml
  # add links to definitions in our API registry by using a fully qualified URL.
stylesheets:
  - https://fonts.googleapis.com/css?family=Roboto:300,400,600,700
  - https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700&display=swap
  - './static/styleOverrides.css'
#ga:
  # you can use any options here from https://www.gatsbyjs.org/packages/gatsby-plugin-google-analytics/
  # note that GA doesn't work in DEV
#  trackingId: UA-45997213-1
#scripts:
  - './scripts/footer-loader.js'
nav:

  - label: Training exercises
    page: developer-portal/index.md

  - label: External docs
    icon: ./images/hpe.svg
    href: https://hpe.com
  - search: true

footer:
  copyrightText: Â© 2020 Hewlett Packard Enterprise Development LP
  columns:
    - group:
      items:
        - label: Privacy 
          href: 'https://www.hpe.com/us/en/legal/privacy.html'
          external: true
        - label: Terms of Use
          href: 'https://www.hpe.com/us/en/about/legal/terms-of-use.html'
          external: true
        - label: Add Choices & Cookies
          href: 'https://www.hpe.com/us/en/legal/privacy.html#datacollection'
          external: true
        - label: Do Not Sell My Personal Information
          href: 'https://www.hpe.com/us/en/privacy/personal-information.html'
          external: true
 
  #columns:
    #- group: Legal
    #  items:
    #    - label: Terms of Use
    #      href: 'https://redoc.ly/subscription-agreement/'
    #    - label: Privacy Notice
    #      href: 'https://redoc.ly/privacy-policy/'
    #    - label: Cookie Notice
    #      href: 'https://redoc.ly/privacy-policy/'
    #- group: Support
    #  items:
    #    - label: FAQ
    #      page: faq.md
    #    - label: Contact us
    #      page: contact.mdx
